{"level": "ERROR", "timestamp": "2024-08-02 17:45:07", "message": "An error occurred while retrieving metrics for UE ue1: [Errno 2] No such file or directory: 'C:\\\\Users\\\\snatanzi\\\\Desktop\\\\vs-code\\\\5G_RAN_SIM\\\\5G_RAN_SIM\\\\5G_RAN_SIM\\\\Config_files\\\\Config_files\\\\gNodeB_config.json'", "test_id": "abea0a2f-10a2-4149-9681-bb301aaf63f1"}
{"level": "ERROR", "timestamp": "2024-08-02 17:45:07", "message": "Exception traceback: Traceback (most recent call last):\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\API_Gateway\\API.py\", line 110, in ue_metrics\n    ue_manager = UEManager.get_instance(base_dir)  # Pass the base_dir argument\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 45, in get_instance\n    cls._instance = UEManager(base_dir)\n                    ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\network\\ue_manager.py\", line 33, in __init__\n    self.config = Config(base_dir)\n                  ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\Config_files\\config.py\", line 7, in __init__\n    self.gNodeBs_config = self.load_json_config('gNodeB_config.json')\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\snatanzi\\Desktop\\vs-code\\5G_RAN_SIM\\5G_RAN_SIM\\5G_RAN_SIM\\Config_files\\config.py\", line 16, in load_json_config\n    with open(file_path, 'r') as file:\n         ^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\snatanzi\\\\Desktop\\\\vs-code\\\\5G_RAN_SIM\\\\5G_RAN_SIM\\\\5G_RAN_SIM\\\\Config_files\\\\Config_files\\\\gNodeB_config.json'\n", "test_id": "abea0a2f-10a2-4149-9681-bb301aaf63f1"}
{"level": "INFO", "timestamp": "2024-08-02 17:45:07", "message": "UE IDs to be returned: ['ue1', 'ue2', 'ue3', 'ue4', 'ue5']", "test_id": "abea0a2f-10a2-4149-9681-bb301aaf63f1"}
{"level": "WARNING", "timestamp": "2024-08-02 18:10:24", "message": "UE UE1 not found in the system", "test_id": "3faea5a8-ce95-4de7-99a8-34efb92b68b0"}
